/* eslint-disable linebreak-style */
export const initialState = {
  currentUser: {
    id: '1',
    isAdmin: false,
    name: 'Jessy',
    email: 'testomail@mail.com',
    phone: '339-382-984',
  },
  isLogged: true,
  posts: {
    currentPost: {},
    data: [
      //{
      //id: '1',
      //title: 'Post 1',
      //text:
      //'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris varius feugiat volutpat. Proin a finibus turpis, quis rutrum ante.Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris varius feugiat volutpat. Proin a finibus turpis, quis rutrum ante.',
      //created: '29/04/2022',
      //changed: '30/04/2022',
      //email: 'mail@mailo.com',
      //authorId: '1',
      //name: 'John Doe',
      //status: 'published',
      //price: 63,
      //image: 'https://images.pexels.com/photos/3394221/pexels-photo-3394221.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
      //summary:'Image title1',
      //phone: '111-222-333-444',
      //location: 'Warsaw',
      //},
      //{
      //id: '2',
      //title: 'Post 2',
      //text:
      //'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris varius feugiat volutpat. Proin a finibus turpis, quis rutrum ante.Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris varius feugiat volutpat. Proin a finibus turpis, quis rutrum ante.',
      //created: '29/04/2022',
      //changed: '30/04/2022',
      //email: 'mail@mailo.com',
      //authorId: '1',
      //name: 'John Doe',
      //status: 'published',
      //price: 63,
      //image: 'https://images.pexels.com/photos/11774744/pexels-photo-11774744.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
      //summary:'Image title1',
      //phone: '111-222-333-444',
      //location: 'Warsaw',
      //},
      //{
      //id: '3',
      //title: 'Post 3',
      //text:
      //  'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris varius feugiat volutpat. Proin a finibus turpis, quis rutrum ante.Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris varius feugiat volutpat. Proin a finibus turpis, quis rutrum ante.',
      //created: '29/04/2022',
      //changed: '30/04/2022',
      //email: 'mail@mailo.com',
      //authorId: '1',
      //name: 'John Doe',
      //status: 'published',
      //price: 63,
      //image: 'https://images.pexels.com/photos/5916954/pexels-photo-5916954.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
      //summary:'Image title1',
      //phone: '111-222-333-444',
      //location: 'Warsaw',
      //},
      //{
      //id: '4',
      //title: 'Post 4',
      //text:
      //'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris varius feugiat volutpat. Proin a finibus turpis, quis rutrum ante.Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris varius feugiat volutpat. Proin a finibus turpis, quis rutrum ante.',
      //created: '29/04/2022',
      //changed: '30/04/2022',
      //email: 'mail@mailo.com',
      //authorId: '1',
      //name: 'John Doe',
      //status: 'published',
      //price: 63,
      //image: 'https://images.pexels.com/photos/8903349/pexels-photo-8903349.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
      //summary:'Image title1',
      //phone: '111-222-333-444',
      //location: 'Warsaw',
      //},
      //{
      //id: '5',
      //title: 'Post 5',
      //text:
      //'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris varius feugiat volutpat. Proin a finibus turpis, quis rutrum ante.Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris varius feugiat volutpat. Proin a finibus turpis, quis rutrum ante.',
      //created: '29/04/2022',
      //changed: '30/04/2022',
      //email: 'mail@mailo.com',
      //authorId: '1',
      //name: 'John Doe',
      //status: 'published',
      //price: 63,
      //image: 'https://images.pexels.com/photos/346804/pexels-photo-346804.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
      //summary:'Image title1',
      //phone: '111-222-333-444',
      //location: 'Warsaw',
      //},
      //{
      //id: '6',
      //title: 'Post 6',
      //text:
      //'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris varius feugiat volutpat. Proin a finibus turpis, quis rutrum ante.Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris varius feugiat volutpat. Proin a finibus turpis, quis rutrum ante.',
      //created: '29/04/2022',
      //changed: '30/04/2022',
      //email: 'mail@mailo.com',
      //authorId: '1',
      //name: 'John Doe',
      //status: 'published',
      //price: 63,
      //image: 'https://images.pexels.com/photos/1148496/pexels-photo-1148496.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
      //summary:'Image title1',
      //phone: '111-222-333-444',
      //location: 'Warsaw',
      //},
    ],
    loading: {
      active: false,
      error: false,
    },
  },
};
